In [3]:
import numpy as np
import torch

In [3]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
print(a[mask])

[4 5]


In [4]:
from dataclasses import asdict, dataclass, replace


In [5]:
@dataclass
class Config:
    a: int
    b: float
    c: str

config = Config(a=1, b=2.0, c="hello")
print(config)

Config(a=1, b=2.0, c='hello')


In [6]:
a = [1, 2, 3]
a[0] = 10
print(a)

a = (1, 2, 3)
# a[0] =10  This will raise a TypeError because tuples are immutable


[10, 2, 3]


In [7]:
x = torch.randn((10, 2))
print(x)
print(x[:, 0].unsqueeze(1))

tensor([[ 0.1691,  1.1748],
        [-0.3541, -0.7481],
        [-0.2926, -1.0852],
        [ 1.1338,  0.7729],
        [-0.7332, -0.4989],
        [ 1.8892, -0.4579],
        [ 1.5762,  0.0506],
        [ 0.5138, -0.1995],
        [ 0.5486,  0.6019],
        [ 0.6713, -0.9087]])
tensor([[ 0.1691],
        [-0.3541],
        [-0.2926],
        [ 1.1338],
        [-0.7332],
        [ 1.8892],
        [ 1.5762],
        [ 0.5138],
        [ 0.5486],
        [ 0.6713]])


In [12]:
def complex_abs2(z: torch.Tensor) -> torch.Tensor:
    return z.real.square() + z.imag.square()

z = torch.tensor([1 + 2j, 3 + 4j])
print(complex_abs2(z))

tensor([ 5., 25.])


In [2]:
import torch
import torch.autograd as autograd

x = torch.tensor([[2.0]], requires_grad=True)  # x = 2

u = x**2   # u = 4

In [3]:
du = autograd.grad(u, x, torch.ones_like(u), create_graph=True)[0]

# second derivative
d2u = autograd.grad(du, x, torch.ones_like(du))[0]

In [12]:
z = torch.complex(torch.tensor([1.0]), torch.tensor([2.0]))
print(z.dtype)

torch.complex64


In [24]:
x = torch.linspace(0, 1, 10).unsqueeze(1)
print(x)
print(x[1, 0])

torch.zeros(x.shape)

mask = x[:, 0] > 0.5
print(x[mask])

tensor([[0.0000],
        [0.1111],
        [0.2222],
        [0.3333],
        [0.4444],
        [0.5556],
        [0.6667],
        [0.7778],
        [0.8889],
        [1.0000]])
tensor(0.1111)
tensor([[0.5556],
        [0.6667],
        [0.7778],
        [0.8889],
        [1.0000]])


In [8]:
from pydoe import lhs
import numpy as np
np.random.seed(1234)
print(lhs(1, 10))
print(lhs(1, 10))

[[0.06970091]
 [0.1795988 ]
 [0.33534469]
 [0.41565663]
 [0.77455976]
 [0.93432196]
 [0.51690129]
 [0.89192519]
 [0.26541704]
 [0.68907868]]
[[0.62867805]
 [0.25642341]
 [0.5975688 ]
 [0.01902051]
 [0.77154471]
 [0.11283924]
 [0.45828674]
 [0.90145882]
 [0.86128254]
 [0.33408618]]


In [2]:
import numpy as np
np.clip(np.array([-1, 0, 1, 2]), 0, 2)

array([0, 0, 1, 2])

In [14]:
torch.randperm(10)
tensor_1 = torch.rand(5).unsqueeze(1)
tensor_2 = torch.rand(5).unsqueeze(1)
print(tensor_2)
torch.cat([tensor_1, tensor_2])

tensor([[0.2005],
        [0.5131],
        [0.0980],
        [0.4450],
        [0.5602]])


tensor([[0.7831],
        [0.1662],
        [0.0688],
        [0.9351],
        [0.3598],
        [0.2005],
        [0.5131],
        [0.0980],
        [0.4450],
        [0.5602]])

In [15]:
x = torch.tensor([[0.0], [0.25], [0.5], [0.75], [1.0]])

print("Before shuffling:")
print(x)

# Shuffle
perm = torch.randperm(x.shape[0])
x_shuffled = x[perm]

print("\nPermutation indices:", perm)
print("After shuffling:")
print(x_shuffled)

Before shuffling:
tensor([[0.0000],
        [0.2500],
        [0.5000],
        [0.7500],
        [1.0000]])

Permutation indices: tensor([2, 3, 4, 1, 0])
After shuffling:
tensor([[0.5000],
        [0.7500],
        [1.0000],
        [0.2500],
        [0.0000]])


In [5]:
import torch

x = torch.tensor([1, 2, 3, 4, 5]).unsqueeze(1)
x_new = torch.where(x > 3, 5, -1)
print(x_new)

tensor([[-1],
        [-1],
        [-1],
        [ 5],
        [ 5]])


In [3]:
from pydoe import lhs

print(torch.tensor(lhs(1, 10)))

tensor([[0.0310],
        [0.1315],
        [0.8164],
        [0.6670],
        [0.3795],
        [0.9923],
        [0.2535],
        [0.4048],
        [0.7181],
        [0.5150]], dtype=torch.float64)
